=== malaise/ada/usr/misc/variables.dtd
<?xml version="1.1"?>
<!-- DTD for Variable definitions -->
<!-- This allows defining several variables -->
<!ATTLIST Variables>
<!ELEMENT Variables (Var)*>

<!-- Each variable must have a name and a type -->
<!--  and is defined by a value -->
<!ATTLIST Var Name CDATA #REQUIRED 
              Type (Str|Int) "Str">
<!ELEMENT Var (#PCDATA)>

=== malaise/ada/usr/misc/variables.xml
<?xml version="1.1"?>
<!-- Definition of variables for test of program "comp_vars" -->
<!DOCTYPE Variables SYSTEM "variables.dtd">
<!-- After Doctype -->

<Variables>
  <!-- Below root -->
  <Var Name="V1" Type="Int">5</Var>
  <Var Name="PATH">${PATH}:/usr/local/bin</Var>
  <Var Name="V2" Type="Int">5*${V1}*${V1}</Var>
  <Var Name="V3" Type="Str">${V1}*${V2}</Var>
  <Var Name="V4"/>
  <Var Name="V2" Type="Int">${V3}*2</Var>
  <!-- Comp_var will report error if variable SET_ME is not set -->
  <Var Name="Fail" Type="Str">${SET_ME}</Var>
</Variables>
<!-- A comment in tail -->
