=== malaise/ada/reposit/Afpx.dtd
<?xml version="1.1"?>
<!-- DTD for Afpx xml definition -->

<!-- General Informations -->
<!-- ==================== -->
<!-- Only Mixed_Case keywords are accepted (not lowercase nor UPPERCASE) -->
<!-- Rows are from 0 to 255 -->
<!-- Cols are from 0 to 255 -->

<!-- Syntax and semantic of the descriptor file -->
<!-- ========================================== -->
<!ATTLIST Afpx_Descriptors Width CDATA #IMPLIED
                           Height CDATA #IMPLIED>

<!-- Afpx_Descriptors allows defining the screen size for all descriptors -->
<!--  Default are a Height of 25 and a Width of 80 -->
<!ELEMENT Afpx_Descriptors (Var*,Descriptor*)>

<!-- Between descriptors, it is possible to define and overwrite variables -->
<!--  A variable name must be <Identifier>[{.<Idenfier>}] the Ada way. -->
<!--  Value can be string or number, and contain some ${Variable} -->
<!ELEMENT Var EMPTY>
<!ATTLIST Var Name  NMTOKEN #REQUIRED
              Value CDATA   #REQUIRED>

<!-- The Afpx_Descriptors is made of several descriptors -->
<!-- Descriptor Num has to be positive range 1 .. 50 and sole (no double) -->
<!ATTLIST Descriptor Num NMTOKEN #REQUIRED>

<!-- A descriptor allows defining one optional list then fields -->
<!-- Before and between them, it is possible to define and overwrite -->
<!--  variables that are valid in the descriptor only -->
<!ELEMENT Descriptor (Var*, List?,(Var|Field)*)>

<!-- List has to be defined none or once per descriptor, at the beginning -->
<!-- List (like fields) is defined by a geometry and colors -->
<!ATTLIST List>
<!ELEMENT List (Geometry,Colors)>

<!-- Field Num has to be within Field_Range (1 .. 200), strictly crescent -->
<!-- within one descriptor, no "hole", no double are allowed -->
<!ATTLIST Field Num NMTOKEN #REQUIRED Kind (Put|Button|Get) #REQUIRED>
<!-- Field are defined by a geometry and colors -->
<!-- Fields also allow defining an initial content (several rows and cols) -->
<!ELEMENT Field (Geometry,Colors,Init*)>

<!-- Geometry must define at least one row and one col -->
<!-- Geometry must not make the field overlap with another field of the -->
<!--  descriptor. Geometry of a Get field must define only one row -->
<!ELEMENT Geometry EMPTY>
<!ATTLIST Geometry Up  CDATA #REQUIRED Left  CDATA #REQUIRED
                   Low CDATA #REQUIRED Right CDATA #REQUIRED>

<!-- Foreground color must be of Colors for Put fields -->
<!--  and of Basic_Colors for Button, Get and List -->
<!-- Background color and Selected color must be Basic_Colors -->
<!-- Blink is mandatory (True or False) for Put fields and must not be -->
<!--  specified for List, Button and Get fields -->
<!-- Selected color is mandatory for List and Get fields and -->
<!--  must not be specified for Put and Button -->
<!-- Summary of color combinations -->
<!-- ============================= -->
<!-- Type  |   Foreground  Blink  Background  Selected -->
<!-- ================================================= -->
<!-- Put   |   X Colors    X      X Basic -->
<!-- Button|   X Basic            X Basic -->
<!-- Get   |   X Basic            X Basic     X Basic -->
<!-- List  |   X Basic            X Basic     X Basic -->
<!-- ================================================ -->
<!ELEMENT Colors EMPTY>
<!ENTITY % Basic_Colors "Black|Blue|Green|Cyan|Red|Magenta|Brown|Light_Gray">
<!ENTITY % Colors "%Basic_Colors;|
                   Dark_Gray|Light_Blue|Light_Green|Orange|Yellow|White">
<!ENTITY % Blink "True|False">
<!ATTLIST Colors Foreground CDATA #REQUIRED
                 Blink CDATA #IMPLIED
                 Background CDATA #REQUIRED
                 Selected CDATA #IMPLIED>

<!-- Init Row has to be compatible with Geometry -->
<!-- Init Col has to be compatible with Geometry -->
<!-- Init string has to be compatible with Geometry and Init Col -->
<!ELEMENT Init (#PCDATA)>
<!ATTLIST Init Row CDATA #REQUIRED Col CDATA #REQUIRED
               xml:space (default|preserve) "preserve">

=== malaise/ada/usr/renardeau/Afpx.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE Afpx_Descriptors SYSTEM "../../reposit/Afpx.dtd">

<!-- For renardeau -->
<Afpx_Descriptors Height="29" Width="40">
  <Color_Definitions>
    <Color_Definition Id="Color09" Color="Dark_Grey"/>
  </Color_Definitions>

  <!-- Main screen -->
  <Descriptor Num="1" Background="Light_Grey">

    <Var Name="TxtStart"  Value="${Screen.Width}-16"/>

    <!-- Title -->
    <Field Num="1" Kind="Put">
      <Geometry Up="1" Left="0" Height="1" Width="${Screen.Width}"/>
      <Colors Foreground="Black" Background="Light_Grey" />
      <Init Row="0" Col="12">R E N A R D E A U</Init>
    </Field>

    <!-- Base numbers (6) -->
    <Field Num="2" Kind="Put">
      <Geometry Up="${Field_1.Low}+2" Left="1"
                Height="1" Width="3"/>
      <Colors Foreground="Black" Background="Light_Grey" />
    </Field>
    <Field Num="3" Kind="Put">
      <Geometry Up="${Field_1.Low}+2" Left="${Field_2.Right}+2"
                Height="1" Width="3"/>
      <Colors Foreground="Black" Background="Light_Grey" />
    </Field>
    <Field Num="4" Kind="Put">
      <Geometry Up="${Field_1.Low}+2" Left="${Field_3.Right}+2"
                Height="1" Width="3"/>
      <Colors Foreground="Black" Background="Light_Grey" />
    </Field>
    <Field Num="5" Kind="Put">
      <Geometry Up="${Field_1.Low}+2" Left="${Field_4.Right}+2"
                Height="1" Width="3"/>
      <Colors Foreground="Black" Background="Light_Grey" />
    </Field>
    <Field Num="6" Kind="Put">
      <Geometry Up="${Field_1.Low}+2" Left="${Field_5.Right}+2"
                Height="1" Width="3"/>
      <Colors Foreground="Black" Background="Light_Grey" />
    </Field>
    <Field Num="7" Kind="Put">
      <Geometry Up="${Field_1.Low}+2" Left="${Field_6.Right}+2"
                Height="1" Width="3"/>
      <Colors Foreground="Black" Background="Light_Grey" />
    </Field>
    <!-- Target number -->
    <Field Num="8" Kind="Put">
      <Geometry Up="${Field_1.Low}+2" Left="${Screen.Right}-3"
                Height="1" Width="3"/>
      <Colors Foreground="Black" Background="Light_Grey" />
    </Field>

    <!-- Buttons -->
    <Field Num="9" Kind="Button">
      <Geometry Up="${Field_2.Low}+2" Left="1"
                Height="3" Width="4"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="1" Col="1">10</Init>
    </Field>
    <Field Num="10" Kind="Button">
      <Geometry Up="${Field_2.Low}+2" Left="${Field_9.Right}+2"
                Height="3" Width="4"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="1" Col="1">25</Init>
    </Field>
    <Field Num="11" Kind="Button">
      <Geometry Up="${Field_2.Low}+2" Left="${Field_10.Right}+2"
                Height="3" Width="4"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="1" Col="1">50</Init>
    </Field>
    <Field Num="12" Kind="Button">
      <Geometry Up="${Field_2.Low}+2" Left="${Field_11.Right}+2"
                Height="3" Width="4"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="1" Col="1">75</Init>
    </Field>
    <Field Num="13" Kind="Button">
      <Geometry Up="${Field_2.Low}+2" Left="${Field_12.Right}+2"
                Height="3" Width="5"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="1" Col="1">100</Init>
    </Field>

    <Field Num="14" Kind="Button">
      <Geometry Up="${Field_9.Low}+2" Left="2"
                Height="3" Width="5"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="1" Col="2">7</Init>
    </Field>
    <Field Num="15" Kind="Button">
      <Geometry Up="${Field_9.Low}+2" Left="${Field_14.Right}+2"
                Height="3" Width="5"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="1" Col="2">8</Init>
    </Field>
    <Field Num="16" Kind="Button">
      <Geometry Up="${Field_9.Low}+2" Left="${Field_15.Right}+2"
                Height="3" Width="5"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="1" Col="2">9</Init>
    </Field>

    <Field Num="17" Kind="Button">
      <Geometry Up="${Field_14.Low}+2" Left="${Field_14.Left}"
                Height="3" Width="5"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="1" Col="2">4</Init>
    </Field>
    <Field Num="18" Kind="Button">
      <Geometry Up="${Field_14.Low}+2" Left="${Field_17.Right}+2"
                Height="3" Width="5"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="1" Col="2">5</Init>
    </Field>
    <Field Num="19" Kind="Button">
      <Geometry Up="${Field_14.Low}+2" Left="${Field_18.Right}+2"
                Height="3" Width="5"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="1" Col="2">6</Init>
    </Field>

    <Field Num="20" Kind="Button">
      <Geometry Up="${Field_17.Low}+2" Left="${Field_14.Left}"
                Height="3" Width="5"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="1" Col="2">1</Init>
    </Field>
    <Field Num="21" Kind="Button">
      <Geometry Up="${Field_17.Low}+2" Left="${Field_20.Right}+2"
                Height="3" Width="5"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="1" Col="2">2</Init>
    </Field>
    <Field Num="22" Kind="Button">
      <Geometry Up="${Field_17.Low}+2" Left="${Field_21.Right}+2"
                Height="3" Width="5"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="1" Col="2">3</Init>
    </Field>

    <Field Num="23" Kind="Button">
      <Geometry Up="${Field_20.Low}+2" Left="${Field_20.Left}"
                Height="3" Width="5"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="1" Col="2">0</Init>
    </Field>
    <Field Num="24" Kind="Button">
      <Geometry Up="${Field_20.Low}+2" Left="${Field_23.Right}+2"
                Height="3" Right="${Field_22.Right}"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="1" Col="1">E N T E R</Init>
    </Field>

    <Field Num="25" Kind="Button">
      <Geometry Up="${Field_23.Low}+2" Left="${Field_23.Left}"
                Height="3" Width="7"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="1" Col="1">CLEAR</Init>
    </Field>
    <Field Num="26" Kind="Button">
      <Geometry Up="${Field_23.Low}+2" Right="${Field_24.Right}"
                Height="3" Width="7"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="1" Col="1">RESET</Init>
    </Field>

    <!-- Result and computation -->
    <Field Num="27" Kind="Put">
      <Geometry Up="${Field_14.Up}" Left="${Field_8.Left}"
                Height="1" Width="3"/>
      <Colors Foreground="Lime_Green" Background="Light_Grey" />
    </Field>
    <Field Num="28" Kind="Put">
      <Geometry Up="${Field_27.Low}+2" Left="${TxtStart}"
                Height="1" Width="15"/>
      <Colors Foreground="Black" Background="Light_Grey" />
    </Field>
    <Field Num="29" Kind="Put">
      <Geometry Up="${Field_28.Low}+2" Left="${TxtStart}"
                Height="1" Width="15"/>
      <Colors Foreground="Black" Background="Light_Grey" />
    </Field>
    <Field Num="30" Kind="Put">
      <Geometry Up="${Field_29.Low}+2" Left="${TxtStart}"
                Height="1" Width="15"/>
      <Colors Foreground="Black" Background="Light_Grey" />
    </Field>
    <Field Num="31" Kind="Put">
      <Geometry Up="${Field_30.Low}+2" Left="${TxtStart}"
                Height="1" Width="15"/>
      <Colors Foreground="Black" Background="Light_Grey" />
    </Field>
    <Field Num="32" Kind="Put">
      <Geometry Up="${Field_31.Low}+2" Left="${TxtStart}"
                Height="1" Width="15"/>
      <Colors Foreground="Black" Background="Light_Grey" />
    </Field>

    <!-- OK and EXIT -->
    <Field Num="33" Kind="Button">
      <Geometry Up="${Field_26.Up}" Left="${Field_26.Right}+3"
                Height="3" Width="9"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="1" Col="3">O K</Init>
    </Field>
    <Field Num="34" Kind="Button">
      <Geometry Up="${Field_33.Up}" Right="${Screen.Width}-2"
                Height="3" Width="6"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="1" Col="1">EXIT</Init>
    </Field>

  </Descriptor>

</Afpx_Descriptors>

=== malaise/ada/usr/regex/Afpx.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE Afpx_Descriptors SYSTEM "../../reposit/Afpx.dtd">
<!-- For regex -->

<Afpx_Descriptors Height="30" Width="94">

  <Descriptor Num="1" Background="Light_Grey" Name="Main">

    <!-- Title -->
    <Field Num="1" Kind="Put">
      <Geometry Up="0" Left="45" Height="1" Width="5"/>
      <Colors Foreground="Black" Background="Light_Grey"/>
      <Init Row="0" Col="0">Regex</Init>
    </Field>

    <!-- Regex -->
    <Field Num="2" Kind="Put">
      <Geometry Up="${Field_1.Low}+2" Left="1" Height="1" Width="22"/>
      <Colors Foreground="Black" Background="Light_Grey"/>
      <Init Row="0" Col="0">The regular expression</Init>
    </Field>
    <Field Num="3" Kind="Put">
      <Geometry Up="${Field_2.Up}" Left="${Field_2.Right}+5" Height="1"
                Width="14"/>
      <Colors Foreground="Black" Background="Light_Grey"/>
      <Init Row="0" Col="0">Case sensitive</Init>
    </Field>
    <Field Num="4" Kind="Button" Name="Case_Sensitive">
      <Geometry Up="${Field_3.Up}" Left="${Field_3.Right}+2" Height="1"
                Width="1"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="0" Col="0">X</Init>
    </Field>

    <Field Num="5" Kind="Get" Name="Regex">
      <Geometry Up="${Field_2.Low}+1" Left="1" Height="1"
                Width="${Screen.Width}-2"/>
      <Colors Foreground="Black" Background="Light_Blue" Selected="White"/>
    </Field>

    <!-- Text to search in -->
    <Var Name="Text_Len" Value="99"/>
    <Field Num="6" Kind="Put">
      <Geometry Up="${Field_5.Low}+2" Right="9" Height="1" Width="9"/>
      <Colors Foreground="Black" Background="Light_Grey"/>
      <Init Row="0" Col="0">From line</Init>
    </Field>
    <Field Num="7" Kind="Put">
      <Geometry Up="${Field_5.Low}+2" Left="13" Height="1" Width="17"/>
      <Colors Foreground="Black" Background="Light_Grey"/>
      <Init Row="0" Col="0">The text to check</Init>
    </Field>
    <Field Num="8" Kind="Put" Name="Cursor">
      <Geometry Up="${Field_7.Low}+1" Right="${Field_7.Left}-4" Height="9"
                Width="2"/>
      <Colors Foreground="Black" Background="Light_Grey"/>
      <Init Row="0" Col="0">-></Init>
    </Field>
    <Field Num="9" Kind="Get" Name="Text1">
      <Geometry Up="${Field_7.Low}+1" Right="${Screen.Right}-1" Height="1"
                Width="80"/>
      <Get_Tuning Data_Len="${Text_Len}" Move_Next="True"/>
      <Colors Foreground="Black" Background="Light_Blue" Selected="White"/>
    </Field>
    <Field Num="10" Kind="Get" Name="Text2">
      <Geometry Up="${Field_9.Low}+1" Left="${Field_9.Left}" Height="1"
                Right="${Field_9.Right}"/>
      <Get_Tuning Data_Len="${Text_Len}" Move_Prev="True" Move_Next="True"/>
      <Colors Foreground="Black" Background="Light_Blue" Selected="White"/>
    </Field>
    <Field Num="11" Kind="Get" Name="Text3">
      <Geometry Up="${Field_10.Low}+1" Left="${Field_9.Left}" Height="1"
                Right="${Field_9.Right}"/>
      <Get_Tuning Data_Len="${Text_Len}" Move_Prev="True" Move_Next="True"/>
      <Colors Foreground="Black" Background="Light_Blue" Selected="White"/>
    </Field>
    <Field Num="12" Kind="Get" Name="Text4">
      <Geometry Up="${Field_11.Low}+1" Left="${Field_9.Left}" Height="1"
                Right="${Field_9.Right}"/>
      <Get_Tuning Data_Len="${Text_Len}" Move_Prev="True" Move_Next="True"/>
      <Colors Foreground="Black" Background="Light_Blue" Selected="White"/>
    </Field>
    <Field Num="13" Kind="Get" Name="Text5">
      <Geometry Up="${Field_12.Low}+1" Left="${Field_9.Left}" Height="1"
                Right="${Field_9.Right}"/>
      <Get_Tuning Data_Len="${Text_Len}" Move_Prev="True" Move_Next="True"/>
      <Colors Foreground="Black" Background="Light_Blue" Selected="White"/>
    </Field>
    <Field Num="14" Kind="Get" Name="Text6">
      <Geometry Up="${Field_13.Low}+1" Left="${Field_9.Left}" Height="1"
                Right="${Field_9.Right}"/>
      <Get_Tuning Data_Len="${Text_Len}" Move_Prev="True" Move_Next="True"/>
      <Colors Foreground="Black" Background="Light_Blue" Selected="White"/>
    </Field>
    <Field Num="15" Kind="Get" Name="Text7">
      <Geometry Up="${Field_14.Low}+1" Left="${Field_9.Left}" Height="1"
                Right="${Field_9.Right}"/>
      <Get_Tuning Data_Len="${Text_Len}" Move_Prev="True" Move_Next="True"/>
      <Colors Foreground="Black" Background="Light_Blue" Selected="White"/>
    </Field>
    <Field Num="16" Kind="Get" Name="Text8">
      <Geometry Up="${Field_15.Low}+1" Left="${Field_9.Left}" Height="1"
                Right="${Field_9.Right}"/>
      <Get_Tuning Data_Len="${Text_Len}" Move_Prev="True" Move_Next="True"/>
      <Colors Foreground="Black" Background="Light_Blue" Selected="White"/>
    </Field>
    <Field Num="17" Kind="Get" Name="Text9">
      <Geometry Up="${Field_16.Low}+1" Left="${Field_9.Left}" Height="1"
                Right="${Field_9.Right}"/>
      <Get_Tuning Data_Len="${Text_Len}" Move_Prev="True" Move_Next="True"/>
      <Colors Foreground="Black" Background="Light_Blue" Selected="White"/>
    </Field>
    <Field Num="18" Kind="Put">
      <Geometry Up="${Field_9.Up}" Left="${Field_9.Left}-2" Height="9"
                Width="1"/>
      <Colors Foreground="Black" Background="Light_Grey"/>
      <Init Row="0" Col="0">1</Init>
      <Init Row="1" Col="0">2</Init>
      <Init Row="2" Col="0">3</Init>
      <Init Row="3" Col="0">4</Init>
      <Init Row="4" Col="0">5</Init>
      <Init Row="5" Col="0">6</Init>
      <Init Row="6" Col="0">7</Init>
      <Init Row="7" Col="0">8</Init>
      <Init Row="8" Col="0">9</Init>
    </Field>

    <!-- Matching result -->
    <Field Num="19" Kind="Put">
      <Geometry Up="${Field_17.Low}+2" Left="1" Height="1" Width="15"/>
      <Colors Foreground="Black" Background="Light_Grey"/>
      <Init Row="0" Col="0">Matches at line</Init>
    </Field>
    <Field Num="20" Kind="Put" Name="Line">
      <Geometry Up="${Field_19.Up}" Left="${Field_19.Right}+2" Height="1"
                Width="1"/>
      <Colors Foreground="Black" Background="Light_Grey"/>
      <Init Row="0" Col="0">0</Init>
    </Field>
    <Field Num="21" Kind="Put">
      <Geometry Up="${Field_19.Low}+1" Left="1" Height="10" Width="3"/>
      <Colors Foreground="Black" Background="Light_Grey"/>
      <Init Row="0" Col="0">All</Init>
      <Init Row="1" Col="2">1</Init>
      <Init Row="2" Col="2">2</Init>
      <Init Row="3" Col="2">3</Init>
      <Init Row="4" Col="2">4</Init>
      <Init Row="5" Col="2">5</Init>
      <Init Row="6" Col="2">6</Init>
      <Init Row="7" Col="2">7</Init>
      <Init Row="8" Col="2">8</Init>
      <Init Row="9" Col="2">9</Init>
    </Field>
    <!-- (xx-yy) -->
    <Field Num="22" Kind="Put" Name="Ranges">
      <Geometry Up="${Field_21.Up}" Left="${Field_21.Right}+2"
                Height="${Field_21.Height}" Width="7"/>
      <Colors Foreground="Black" Background="Light_Grey"/>
    </Field>
    <Field Num="23" Kind="Put" Name="Result">
      <Geometry Up="${Field_21.Up}" Left="${Field_22.Right}+2"
                Height="${Field_21.Height}" Right="${Screen.Right}-2"/>
      <Colors Foreground="Black" Background="Light_Grey"/>
    </Field>

    <!-- Buttons -->
    <Field Num="24" Kind="Button" Name="Clear_regex">
      <Geometry Up="${Field_21.Low}+2" Left="1" Height="1" Width="13"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="0" Col="1">Clear Regex</Init>
    </Field>
    <Field Num="25" Kind="Button" Name="Clear_Text">
      <Geometry Up="${Field_24.Up}" Left="${Field_24.Right}+4" Height="1"
                Width="12"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="0" Col="1">Clear Text</Init>
    </Field>
    <Field Num="26" Kind="Button" Name="Quit">
      <Geometry Up="${Field_24.Up}" Right="${Screen.Width}-2" Height="1"
                Width="6"/>
      <Colors Foreground="Black" Background="Dark_Grey"/>
      <Init Row="0" Col="1">Exit</Init>
    </Field>
  </Descriptor>

</Afpx_Descriptors>

=== malaise/ada/usr/agite/Afpx.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE Afpx_Descriptors SYSTEM "../../reposit/Afpx.dtd">

<!-- For agite -->
<Afpx_Descriptors Height="42" Width="55">

  <!-- Main screen: explorator --> 
  <Descriptor Num="1" Background="Light_gray">

    <!-- List management setup -->
    <Var Name="LmWidth" Value="8"/>
    <Var Name="LmHOffset" Value="2"/>

    <!-- Title and list -->
    <Var Name="WWidth" Value="${Screen.Width}-${LmWidth}-${LmHOffset}-1"/>
    <List>
      <Geometry Up="6" Left="1" Low="${Screen.Low}-1" Width="${WWidth}"/>
      <Colors Foreground="Black" Background="Magenta" Selected="Green"/>
    </List>
    <Field Num="1" Kind="Put">
      <Geometry Up="0" Left="23" Height="1" Width="9"/>
      <Colors Foreground="Black" Background="Light_gray" Blink="False"/>
      <Init Row="0" Col="0">A G I T E</Init>
    </Field>

    <!-- List management -->
    <Var Name="LmLeft"  Value="${List.Right}+${LmHOffset}"/>
    <Var Name="LmUp"    Value="${List.Up}"/>
    <Var Name="LmSta"   Value="1"/>

    <Field Num="2" Kind="Button">
      <Geometry Up="${LmUp}" Left="${LmLeft}" Height="1" Width="${LmWidth}"/>
      <Colors Foreground="Cyan" Background="Brown"/>
      <Init Row="0" Col="${LmSta}+1">Top</Init>
    </Field>
    <Field Num="3" Kind="Button">
      <Geometry Up="${Field_2.Low}+2" Left="${LmLeft}" Height="3" Width="${LmWidth}"/>
      <Colors Foreground="Cyan" Background="Brown"/>
      <Init Row="1" Col="${LmSta}+1">PgUp </Init>
    </Field>
    <Field Num="4" Kind="Button">
      <Geometry Up="${Field_3.Low}+2" Left="${LmLeft}" Height="1" Width="${LmWidth}"/>
      <Colors Foreground="Cyan" Background="Brown"/>
      <Init Row="0" Col="${LmSta}+2">Up </Init>
    </Field>
    <Field Num="5" Kind="Button">
      <Geometry Up="${Field_4.Low}+2" Left="${LmLeft}" Height="1" Width="${LmWidth}"/>
      <Colors Foreground="Cyan" Background="Brown"/>
      <Init Row="0" Col="${LmSta}">Center</Init>
    </Field>
    <Field Num="6" Kind="Button">
      <Geometry Up="${Field_5.Low}+2" Left="${LmLeft}" Height="1" Width="${LmWidth}"/>
      <Colors Foreground="Cyan" Background="Brown"/>
      <Init Row="0" Col="${LmSta}+1">Down</Init>
    </Field>
    <Field Num="7" Kind="Button">
      <Geometry Up="${Field_6.Low}+2" Left="${LmLeft}" Height="3" Width="${LmWidth}"/>
      <Colors Foreground="Cyan" Background="Brown"/>
      <Init Row="1" Col="${LmSta}">PgDown</Init>
    </Field>
    <Field Num="8" Kind="Button">
      <Geometry Up="${Field_7.Low}+2" Left="${LmLeft}" Height="1" Width="${LmWidth}"/>
      <Colors Foreground="Cyan" Background="Brown"/>
      <Init Row="0" Col="${LmSta}">Bottom</Init>
    </Field>

  </Descriptor>
</Afpx_Descriptors>
