=== malaise/ada/reposit/Byte2unicode.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD for Byte_To_Unicode -->
<!-- +++++++++++++++++++++++ -->

<!-- All the Codes (from 0x00 to 0xFF) must be defined -->
<!-- In any order -->
<!ELEMENT Map (Code+)>

<!-- Byte can be in decimal or hexadecimal (16#zz# or 0xzz) -->
<!ATTLIST Code Byte CDATA #REQUIRED>
<!-- Code can be in decimal or hexadecimal (16#zz# or 0xzz) -->
<!ELEMENT Code (#PCDATA)>

=== malaise/ada/usr/tests/data/ISO-8859-5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Map SYSTEM "Byte2unicode.dtd">
<Map>
  <Code Byte="16#A1#">16#0401#</Code>
  <Code Byte="16#A2#">16#0402#</Code>
  <Code Byte="16#A3#">16#0403#</Code>
  <Code Byte="16#A4#">16#0404#</Code>
  <Code Byte="16#A5#">16#0405#</Code>
  <Code Byte="16#A6#">16#0406#</Code>
  <Code Byte="16#A7#">16#0407#</Code>
  <Code Byte="16#A8#">16#0408#</Code>
  <Code Byte="16#A9#">16#0409#</Code>
  <Code Byte="16#AA#">16#040A#</Code>
  <Code Byte="16#AB#">16#040B#</Code>
  <Code Byte="16#AC#">16#040C#</Code>
  <Code Byte="16#AE#">16#040E#</Code>
  <Code Byte="16#AF#">16#040F#</Code>
  <Code Byte="16#B0#">16#0410#</Code>
  <Code Byte="16#B1#">16#0411#</Code>
  <Code Byte="16#B2#">16#0412#</Code>
  <Code Byte="16#B3#">16#0413#</Code>
  <Code Byte="16#B4#">16#0414#</Code>
  <Code Byte="16#B5#">16#0415#</Code>
  <Code Byte="16#B6#">16#0416#</Code>
  <Code Byte="16#B7#">16#0417#</Code>
  <Code Byte="16#B8#">16#0418#</Code>
  <Code Byte="16#B9#">16#0419#</Code>
  <Code Byte="16#BA#">16#041A#</Code>
  <Code Byte="16#BB#">16#041B#</Code>
  <Code Byte="16#BC#">16#041C#</Code>
  <Code Byte="16#BD#">16#041D#</Code>
  <Code Byte="16#BE#">16#041E#</Code>
  <Code Byte="16#BF#">16#041F#</Code>
  <Code Byte="16#C0#">16#0420#</Code>
  <Code Byte="16#C1#">16#0421#</Code>
  <Code Byte="16#C2#">16#0422#</Code>
  <Code Byte="16#C3#">16#0423#</Code>
  <Code Byte="16#C4#">16#0424#</Code>
  <Code Byte="16#C5#">16#0425#</Code>
  <Code Byte="16#C6#">16#0426#</Code>
  <Code Byte="16#C7#">16#0427#</Code>
  <Code Byte="16#C8#">16#0428#</Code>
  <Code Byte="16#C9#">16#0429#</Code>
  <Code Byte="16#CA#">16#042A#</Code>
  <Code Byte="16#CB#">16#042B#</Code>
  <Code Byte="16#CC#">16#042C#</Code>
  <Code Byte="16#CD#">16#042D#</Code>
  <Code Byte="16#CE#">16#042E#</Code>
  <Code Byte="16#CF#">16#042F#</Code>
  <Code Byte="16#D0#">16#0430#</Code>
  <Code Byte="16#D1#">16#0431#</Code>
  <Code Byte="16#D2#">16#0432#</Code>
  <Code Byte="16#D3#">16#0433#</Code>
  <Code Byte="16#D4#">16#0434#</Code>
  <Code Byte="16#D5#">16#0435#</Code>
  <Code Byte="16#D6#">16#0436#</Code>
  <Code Byte="16#D7#">16#0437#</Code>
  <Code Byte="16#D8#">16#0438#</Code>
  <Code Byte="16#D9#">16#0439#</Code>
  <Code Byte="16#DA#">16#043A#</Code>
  <Code Byte="16#DB#">16#043B#</Code>
  <Code Byte="16#DC#">16#043C#</Code>
  <Code Byte="16#DD#">16#043D#</Code>
  <Code Byte="16#DE#">16#043E#</Code>
  <Code Byte="16#DF#">16#043F#</Code>
  <Code Byte="16#E0#">16#0440#</Code>
  <Code Byte="16#E1#">16#0441#</Code>
  <Code Byte="16#E2#">16#0442#</Code>
  <Code Byte="16#E3#">16#0443#</Code>
  <Code Byte="16#E4#">16#0444#</Code>
  <Code Byte="16#E5#">16#0445#</Code>
  <Code Byte="16#E6#">16#0446#</Code>
  <Code Byte="16#E7#">16#0447#</Code>
  <Code Byte="16#E8#">16#0448#</Code>
  <Code Byte="16#E9#">16#0449#</Code>
  <Code Byte="16#EA#">16#044A#</Code>
  <Code Byte="16#EB#">16#044B#</Code>
  <Code Byte="16#EC#">16#044C#</Code>
  <Code Byte="16#ED#">16#044D#</Code>
  <Code Byte="16#EE#">16#044E#</Code>
  <Code Byte="16#EF#">16#044F#</Code>
  <Code Byte="16#F0#">16#2116#</Code>
  <Code Byte="16#F1#">16#0451#</Code>
  <Code Byte="16#F2#">16#0452#</Code>
  <Code Byte="16#F3#">16#0453#</Code>
  <Code Byte="16#F4#">16#0454#</Code>
  <Code Byte="16#F5#">16#0455#</Code>
  <Code Byte="16#F6#">16#0456#</Code>
  <Code Byte="16#F7#">16#0457#</Code>
  <Code Byte="16#F8#">16#0458#</Code>
  <Code Byte="16#F9#">16#0459#</Code>
  <Code Byte="16#FA#">16#045A#</Code>
  <Code Byte="16#FB#">16#045B#</Code>
  <Code Byte="16#FC#">16#045C#</Code>
  <Code Byte="16#FD#">16#00A7#</Code>
  <Code Byte="16#FE#">16#045E#</Code>
  <Code Byte="16#FF#">16#045F#</Code>
</Map>

=== malaise/ada/usr/tests/data/ISO-8859-7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Map SYSTEM "byte2unicode.dtd">
<Map>
  <Code Byte="16#00#">16#0000#</Code>
  <Code Byte="16#01#">16#0001#</Code>
  <Code Byte="16#02#">16#0002#</Code>
  <Code Byte="16#03#">16#0003#</Code>
  <Code Byte="16#04#">16#0004#</Code>
  <Code Byte="16#05#">16#0005#</Code>
  <Code Byte="16#06#">16#0006#</Code>
  <Code Byte="16#07#">16#0007#</Code>
  <Code Byte="16#08#">16#0008#</Code>
  <Code Byte="16#09#">16#0009#</Code>
  <Code Byte="16#0A#">16#000A#</Code>
  <Code Byte="16#0B#">16#000B#</Code>
  <Code Byte="16#0C#">16#000C#</Code>
  <Code Byte="16#0D#">16#000D#</Code>
  <Code Byte="16#0E#">16#000E#</Code>
  <Code Byte="16#0F#">16#000F#</Code>
  <Code Byte="16#10#">16#0010#</Code>
  <Code Byte="16#11#">16#0011#</Code>
  <Code Byte="16#12#">16#0012#</Code>
  <Code Byte="16#13#">16#0013#</Code>
  <Code Byte="16#14#">16#0014#</Code>
  <Code Byte="16#15#">16#0015#</Code>
  <Code Byte="16#16#">16#0016#</Code>
  <Code Byte="16#17#">16#0017#</Code>
  <Code Byte="16#18#">16#0018#</Code>
  <Code Byte="16#19#">16#0019#</Code>
  <Code Byte="16#1A#">16#001A#</Code>
  <Code Byte="16#1B#">16#001B#</Code>
  <Code Byte="16#1C#">16#001C#</Code>
  <Code Byte="16#1D#">16#001D#</Code>
  <Code Byte="16#1E#">16#001E#</Code>
  <Code Byte="16#1F#">16#001F#</Code>
  <Code Byte="16#20#">16#0020#</Code>
  <Code Byte="16#21#">16#0021#</Code>
  <Code Byte="16#22#">16#0022#</Code>
  <Code Byte="16#23#">16#0023#</Code>
  <Code Byte="16#24#">16#0024#</Code>
  <Code Byte="16#25#">16#0025#</Code>
  <Code Byte="16#26#">16#0026#</Code>
  <Code Byte="16#27#">16#0027#</Code>
  <Code Byte="16#28#">16#0028#</Code>
  <Code Byte="16#29#">16#0029#</Code>
  <Code Byte="16#2A#">16#002A#</Code>
  <Code Byte="16#2B#">16#002B#</Code>
  <Code Byte="16#2C#">16#002C#</Code>
  <Code Byte="16#2D#">16#002D#</Code>
  <Code Byte="16#2E#">16#002E#</Code>
  <Code Byte="16#2F#">16#002F#</Code>
  <Code Byte="16#30#">16#0030#</Code>
  <Code Byte="16#31#">16#0031#</Code>
  <Code Byte="16#32#">16#0032#</Code>
  <Code Byte="16#33#">16#0033#</Code>
  <Code Byte="16#34#">16#0034#</Code>
  <Code Byte="16#35#">16#0035#</Code>
  <Code Byte="16#36#">16#0036#</Code>
  <Code Byte="16#37#">16#0037#</Code>
  <Code Byte="16#38#">16#0038#</Code>
  <Code Byte="16#39#">16#0039#</Code>
  <Code Byte="16#3A#">16#003A#</Code>
  <Code Byte="16#3B#">16#003B#</Code>
  <Code Byte="16#3C#">16#003C#</Code>
  <Code Byte="16#3D#">16#003D#</Code>
  <Code Byte="16#3E#">16#003E#</Code>
  <Code Byte="16#3F#">16#003F#</Code>
  <Code Byte="16#40#">16#0040#</Code>
  <Code Byte="16#41#">16#0041#</Code>
  <Code Byte="16#42#">16#0042#</Code>
  <Code Byte="16#43#">16#0043#</Code>
  <Code Byte="16#44#">16#0044#</Code>
  <Code Byte="16#45#">16#0045#</Code>
  <Code Byte="16#46#">16#0046#</Code>
  <Code Byte="16#47#">16#0047#</Code>
  <Code Byte="16#48#">16#0048#</Code>
  <Code Byte="16#49#">16#0049#</Code>
  <Code Byte="16#4A#">16#004A#</Code>
  <Code Byte="16#4B#">16#004B#</Code>
  <Code Byte="16#4C#">16#004C#</Code>
  <Code Byte="16#4D#">16#004D#</Code>
  <Code Byte="16#4E#">16#004E#</Code>
  <Code Byte="16#4F#">16#004F#</Code>
  <Code Byte="16#50#">16#0050#</Code>
  <Code Byte="16#51#">16#0051#</Code>
  <Code Byte="16#52#">16#0052#</Code>
  <Code Byte="16#53#">16#0053#</Code>
  <Code Byte="16#54#">16#0054#</Code>
  <Code Byte="16#55#">16#0055#</Code>
  <Code Byte="16#56#">16#0056#</Code>
  <Code Byte="16#57#">16#0057#</Code>
  <Code Byte="16#58#">16#0058#</Code>
  <Code Byte="16#59#">16#0059#</Code>
  <Code Byte="16#5A#">16#005A#</Code>
  <Code Byte="16#5B#">16#005B#</Code>
  <Code Byte="16#5C#">16#005C#</Code>
  <Code Byte="16#5D#">16#005D#</Code>
  <Code Byte="16#5E#">16#005E#</Code>
  <Code Byte="16#5F#">16#005F#</Code>
  <Code Byte="16#60#">16#0060#</Code>
  <Code Byte="16#61#">16#0061#</Code>
  <Code Byte="16#62#">16#0062#</Code>
  <Code Byte="16#63#">16#0063#</Code>
  <Code Byte="16#64#">16#0064#</Code>
  <Code Byte="16#65#">16#0065#</Code>
  <Code Byte="16#66#">16#0066#</Code>
  <Code Byte="16#67#">16#0067#</Code>
  <Code Byte="16#68#">16#0068#</Code>
  <Code Byte="16#69#">16#0069#</Code>
  <Code Byte="16#6A#">16#006A#</Code>
  <Code Byte="16#6B#">16#006B#</Code>
  <Code Byte="16#6C#">16#006C#</Code>
  <Code Byte="16#6D#">16#006D#</Code>
  <Code Byte="16#6E#">16#006E#</Code>
  <Code Byte="16#6F#">16#006F#</Code>
  <Code Byte="16#70#">16#0070#</Code>
  <Code Byte="16#71#">16#0071#</Code>
  <Code Byte="16#72#">16#0072#</Code>
  <Code Byte="16#73#">16#0073#</Code>
  <Code Byte="16#74#">16#0074#</Code>
  <Code Byte="16#75#">16#0075#</Code>
  <Code Byte="16#76#">16#0076#</Code>
  <Code Byte="16#77#">16#0077#</Code>
  <Code Byte="16#78#">16#0078#</Code>
  <Code Byte="16#79#">16#0079#</Code>
  <Code Byte="16#7A#">16#007A#</Code>
  <Code Byte="16#7B#">16#007B#</Code>
  <Code Byte="16#7C#">16#007C#</Code>
  <Code Byte="16#7D#">16#007D#</Code>
  <Code Byte="16#7E#">16#007E#</Code>
  <Code Byte="16#7F#">16#007F#</Code>
  <Code Byte="16#80#">16#0080#</Code>
  <Code Byte="16#81#">16#0081#</Code>
  <Code Byte="16#82#">16#0082#</Code>
  <Code Byte="16#83#">16#0083#</Code>
  <Code Byte="16#84#">16#0084#</Code>
  <Code Byte="16#85#">16#0085#</Code>
  <Code Byte="16#86#">16#0086#</Code>
  <Code Byte="16#87#">16#0087#</Code>
  <Code Byte="16#88#">16#0088#</Code>
  <Code Byte="16#89#">16#0089#</Code>
  <Code Byte="16#8A#">16#008A#</Code>
  <Code Byte="16#8B#">16#008B#</Code>
  <Code Byte="16#8C#">16#008C#</Code>
  <Code Byte="16#8D#">16#008D#</Code>
  <Code Byte="16#8E#">16#008E#</Code>
  <Code Byte="16#8F#">16#008F#</Code>
  <Code Byte="16#90#">16#0090#</Code>
  <Code Byte="16#91#">16#0091#</Code>
  <Code Byte="16#92#">16#0092#</Code>
  <Code Byte="16#93#">16#0093#</Code>
  <Code Byte="16#94#">16#0094#</Code>
  <Code Byte="16#95#">16#0095#</Code>
  <Code Byte="16#96#">16#0096#</Code>
  <Code Byte="16#97#">16#0097#</Code>
  <Code Byte="16#98#">16#0098#</Code>
  <Code Byte="16#99#">16#0099#</Code>
  <Code Byte="16#9A#">16#009A#</Code>
  <Code Byte="16#9B#">16#009B#</Code>
  <Code Byte="16#9C#">16#009C#</Code>
  <Code Byte="16#9D#">16#009D#</Code>
  <Code Byte="16#9E#">16#009E#</Code>
  <Code Byte="16#9F#">16#009F#</Code>
  <Code Byte="16#A0#">16#00A0#</Code>
  <Code Byte="16#A1#">16#2018#</Code>
  <Code Byte="16#A2#">16#2019#</Code>
  <Code Byte="16#A3#">16#00A3#</Code>
  <Code Byte="16#A4#">16#20AC#</Code>
  <Code Byte="16#A5#">16#20AF#</Code>
  <Code Byte="16#A6#">16#00A6#</Code>
  <Code Byte="16#A7#">16#00A7#</Code>
  <Code Byte="16#A8#">16#00A8#</Code>
  <Code Byte="16#A9#">16#00A9#</Code>
  <Code Byte="16#AA#">16#037A#</Code>
  <Code Byte="16#AB#">16#00AB#</Code>
  <Code Byte="16#AC#">16#00AC#</Code>
  <Code Byte="16#AD#">16#00AD#</Code>
  <Code Byte="16#AF#">16#2015#</Code>
  <Code Byte="16#B0#">16#00B0#</Code>
  <Code Byte="16#B1#">16#00B1#</Code>
  <Code Byte="16#B2#">16#00B2#</Code>
  <Code Byte="16#B3#">16#00B3#</Code>
  <Code Byte="16#B4#">16#0384#</Code>
  <Code Byte="16#B5#">16#0385#</Code>
  <Code Byte="16#B6#">16#0386#</Code>
  <Code Byte="16#B7#">16#00B7#</Code>
  <Code Byte="16#B8#">16#0388#</Code>
  <Code Byte="16#B9#">16#0389#</Code>
  <Code Byte="16#BA#">16#038A#</Code>
  <Code Byte="16#BB#">16#00BB#</Code>
  <Code Byte="16#BC#">16#038C#</Code>
  <Code Byte="16#BD#">16#00BD#</Code>
  <Code Byte="16#BE#">16#038E#</Code>
  <Code Byte="16#BF#">16#038F#</Code>
  <Code Byte="16#C0#">16#0390#</Code>
  <Code Byte="16#C1#">16#0391#</Code>
  <Code Byte="16#C2#">16#0392#</Code>
  <Code Byte="16#C3#">16#0393#</Code>
  <Code Byte="16#C4#">16#0394#</Code>
  <Code Byte="16#C5#">16#0395#</Code>
  <Code Byte="16#C6#">16#0396#</Code>
  <Code Byte="16#C7#">16#0397#</Code>
  <Code Byte="16#C8#">16#0398#</Code>
  <Code Byte="16#C9#">16#0399#</Code>
  <Code Byte="16#CA#">16#039A#</Code>
  <Code Byte="16#CB#">16#039B#</Code>
  <Code Byte="16#CC#">16#039C#</Code>
  <Code Byte="16#CD#">16#039D#</Code>
  <Code Byte="16#CE#">16#039E#</Code>
  <Code Byte="16#CF#">16#039F#</Code>
  <Code Byte="16#D0#">16#03A0#</Code>
  <Code Byte="16#D1#">16#03A1#</Code>
  <Code Byte="16#D3#">16#03A3#</Code>
  <Code Byte="16#D4#">16#03A4#</Code>
  <Code Byte="16#D5#">16#03A5#</Code>
  <Code Byte="16#D6#">16#03A6#</Code>
  <Code Byte="16#D7#">16#03A7#</Code>
  <Code Byte="16#D8#">16#03A8#</Code>
  <Code Byte="16#D9#">16#03A9#</Code>
  <Code Byte="16#DA#">16#03AA#</Code>
  <Code Byte="16#DB#">16#03AB#</Code>
  <Code Byte="16#DC#">16#03AC#</Code>
  <Code Byte="16#DD#">16#03AD#</Code>
  <Code Byte="16#DE#">16#03AE#</Code>
  <Code Byte="16#DF#">16#03AF#</Code>
  <Code Byte="16#E0#">16#03B0#</Code>
  <Code Byte="16#E1#">16#03B1#</Code>
  <Code Byte="16#E2#">16#03B2#</Code>
  <Code Byte="16#E3#">16#03B3#</Code>
  <Code Byte="16#E4#">16#03B4#</Code>
  <Code Byte="16#E5#">16#03B5#</Code>
  <Code Byte="16#E6#">16#03B6#</Code>
  <Code Byte="16#E7#">16#03B7#</Code>
  <Code Byte="16#E8#">16#03B8#</Code>
  <Code Byte="16#E9#">16#03B9#</Code>
  <Code Byte="16#EA#">16#03BA#</Code>
  <Code Byte="16#EB#">16#03BB#</Code>
  <Code Byte="16#EC#">16#03BC#</Code>
  <Code Byte="16#ED#">16#03BD#</Code>
  <Code Byte="16#EE#">16#03BE#</Code>
  <Code Byte="16#EF#">16#03BF#</Code>
  <Code Byte="16#F0#">16#03C0#</Code>
  <Code Byte="16#F1#">16#03C1#</Code>
  <Code Byte="16#F2#">16#03C2#</Code>
  <Code Byte="16#F3#">16#03C3#</Code>
  <Code Byte="16#F4#">16#03C4#</Code>
  <Code Byte="16#F5#">16#03C5#</Code>
  <Code Byte="16#F6#">16#03C6#</Code>
  <Code Byte="16#F7#">16#03C7#</Code>
  <Code Byte="16#F8#">16#03C8#</Code>
  <Code Byte="16#F9#">16#03C9#</Code>
  <Code Byte="16#FA#">16#03CA#</Code>
  <Code Byte="16#FB#">16#03CB#</Code>
  <Code Byte="16#FC#">16#03CC#</Code>
  <Code Byte="16#FD#">16#03CD#</Code>
  <Code Byte="16#FE#">16#03CE#</Code>
</Map>

=== malaise/ada/usr/tests/data/ISO-8859-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Map SYSTEM "Byte2unicode.dtd">
<Map>
  <Code Byte="16#A1#">16#0126#</Code>
  <Code Byte="16#A2#">16#02D8#</Code>
  <Code Byte="16#A6#">16#0124#</Code>
  <Code Byte="16#A9#">16#0130#</Code>
  <Code Byte="16#AA#">16#015E#</Code>
  <Code Byte="16#AB#">16#011E#</Code>
  <Code Byte="16#AC#">16#0134#</Code>
  <Code Byte="16#AF#">16#017B#</Code>
  <Code Byte="16#B1#">16#0127#</Code>
  <Code Byte="16#B6#">16#0125#</Code>
  <Code Byte="16#B9#">16#0131#</Code>
  <Code Byte="16#BA#">16#015F#</Code>
  <Code Byte="16#BB#">16#011F#</Code>
  <Code Byte="16#BC#">16#0135#</Code>
  <Code Byte="16#BF#">16#017C#</Code>
  <Code Byte="16#C5#">16#010A#</Code>
  <Code Byte="16#C6#">16#0108#</Code>
  <Code Byte="16#D5#">16#0120#</Code>
  <Code Byte="16#D8#">16#011C#</Code>
  <Code Byte="16#DD#">16#016C#</Code>
  <Code Byte="16#DE#">16#015C#</Code>
  <Code Byte="16#E5#">16#010B#</Code>
  <Code Byte="16#E6#">16#0109#</Code>
  <Code Byte="16#F5#">16#0121#</Code>
  <Code Byte="16#F8#">16#011D#</Code>
  <Code Byte="16#FD#">16#016D#</Code>
  <Code Byte="16#FE#">16#015D#</Code>
  <Code Byte="16#FF#">16#02D9#</Code>
</Map>

=== malaise/ada/usr/tests/data/ISO-8859-8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Map SYSTEM "Byte2unicode.dtd">
<Map>
  <Code Byte="16#AA#">16#00D7#</Code>
  <Code Byte="16#BA#">16#00F7#</Code>
  <Code Byte="16#DF#">16#2017#</Code>
  <Code Byte="16#E0#">16#05D0#</Code>
  <Code Byte="16#E1#">16#05D1#</Code>
  <Code Byte="16#E2#">16#05D2#</Code>
  <Code Byte="16#E3#">16#05D3#</Code>
  <Code Byte="16#E4#">16#05D4#</Code>
  <Code Byte="16#E5#">16#05D5#</Code>
  <Code Byte="16#E6#">16#05D6#</Code>
  <Code Byte="16#E7#">16#05D7#</Code>
  <Code Byte="16#E8#">16#05D8#</Code>
  <Code Byte="16#E9#">16#05D9#</Code>
  <Code Byte="16#EA#">16#05DA#</Code>
  <Code Byte="16#EB#">16#05DB#</Code>
  <Code Byte="16#EC#">16#05DC#</Code>
  <Code Byte="16#ED#">16#05DD#</Code>
  <Code Byte="16#EE#">16#05DE#</Code>
  <Code Byte="16#EF#">16#05DF#</Code>
  <Code Byte="16#F0#">16#05E0#</Code>
  <Code Byte="16#F1#">16#05E1#</Code>
  <Code Byte="16#F2#">16#05E2#</Code>
  <Code Byte="16#F3#">16#05E3#</Code>
  <Code Byte="16#F4#">16#05E4#</Code>
  <Code Byte="16#F5#">16#05E5#</Code>
  <Code Byte="16#F6#">16#05E6#</Code>
  <Code Byte="16#F7#">16#05E7#</Code>
  <Code Byte="16#F8#">16#05E8#</Code>
  <Code Byte="16#F9#">16#05E9#</Code>
  <Code Byte="16#FA#">16#05EA#</Code>
  <Code Byte="16#FD#">16#200E#</Code>
  <Code Byte="16#FE#">16#200F#</Code>
</Map>

=== malaise/ada/usr/tests/data/ISO-8859-16.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Map SYSTEM "Byte2unicode.dtd">
<Map>
  <Code Byte="16#A1#">16#0104#</Code>
  <Code Byte="16#A2#">16#0105#</Code>
  <Code Byte="16#A3#">16#0141#</Code>
  <Code Byte="16#A4#">16#20AC#</Code>
  <Code Byte="16#A5#">16#201E#</Code>
  <Code Byte="16#A6#">16#0160#</Code>
  <Code Byte="16#A8#">16#0161#</Code>
  <Code Byte="16#AA#">16#0218#</Code>
  <Code Byte="16#AC#">16#0179#</Code>
  <Code Byte="16#AE#">16#017A#</Code>
  <Code Byte="16#AF#">16#017B#</Code>
  <Code Byte="16#B2#">16#010C#</Code>
  <Code Byte="16#B3#">16#0142#</Code>
  <Code Byte="16#B4#">16#017D#</Code>
  <Code Byte="16#B5#">16#201D#</Code>
  <Code Byte="16#B8#">16#017E#</Code>
  <Code Byte="16#B9#">16#010D#</Code>
  <Code Byte="16#BA#">16#0219#</Code>
  <Code Byte="16#BC#">16#0152#</Code>
  <Code Byte="16#BD#">16#0153#</Code>
  <Code Byte="16#BE#">16#0178#</Code>
  <Code Byte="16#BF#">16#017C#</Code>
  <Code Byte="16#C3#">16#0102#</Code>
  <Code Byte="16#C5#">16#0106#</Code>
  <Code Byte="16#D0#">16#0110#</Code>
  <Code Byte="16#D1#">16#0143#</Code>
  <Code Byte="16#D5#">16#0150#</Code>
  <Code Byte="16#D7#">16#015A#</Code>
  <Code Byte="16#D8#">16#0170#</Code>
  <Code Byte="16#DD#">16#0118#</Code>
  <Code Byte="16#DE#">16#021A#</Code>
  <Code Byte="16#E3#">16#0103#</Code>
  <Code Byte="16#E5#">16#0107#</Code>
  <Code Byte="16#F0#">16#0111#</Code>
  <Code Byte="16#F1#">16#0144#</Code>
  <Code Byte="16#F5#">16#0151#</Code>
  <Code Byte="16#F7#">16#015B#</Code>
  <Code Byte="16#F8#">16#0171#</Code>
  <Code Byte="16#FD#">16#0119#</Code>
  <Code Byte="16#FE#">16#021B#</Code>
</Map>

=== malaise/ada/usr/tests/data/ISO-8859-13.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Map SYSTEM "Byte2unicode.dtd">
<Map>
  <Code Byte="16#A1#">16#201D#</Code>
  <Code Byte="16#A5#">16#201E#</Code>
  <Code Byte="16#A8#">16#00D8#</Code>
  <Code Byte="16#AA#">16#0156#</Code>
  <Code Byte="16#AF#">16#00C6#</Code>
  <Code Byte="16#B4#">16#201C#</Code>
  <Code Byte="16#B8#">16#00F8#</Code>
  <Code Byte="16#BA#">16#0157#</Code>
  <Code Byte="16#BF#">16#00E6#</Code>
  <Code Byte="16#C0#">16#0104#</Code>
  <Code Byte="16#C1#">16#012E#</Code>
  <Code Byte="16#C2#">16#0100#</Code>
  <Code Byte="16#C3#">16#0106#</Code>
  <Code Byte="16#C6#">16#0118#</Code>
  <Code Byte="16#C7#">16#0112#</Code>
  <Code Byte="16#C8#">16#010C#</Code>
  <Code Byte="16#CA#">16#0179#</Code>
  <Code Byte="16#CB#">16#0116#</Code>
  <Code Byte="16#CC#">16#0122#</Code>
  <Code Byte="16#CD#">16#0136#</Code>
  <Code Byte="16#CE#">16#012A#</Code>
  <Code Byte="16#CF#">16#013B#</Code>
  <Code Byte="16#D0#">16#0160#</Code>
  <Code Byte="16#D1#">16#0143#</Code>
  <Code Byte="16#D2#">16#0145#</Code>
  <Code Byte="16#D4#">16#014C#</Code>
  <Code Byte="16#D8#">16#0172#</Code>
  <Code Byte="16#D9#">16#0141#</Code>
  <Code Byte="16#DA#">16#015A#</Code>
  <Code Byte="16#DB#">16#016A#</Code>
  <Code Byte="16#DD#">16#017B#</Code>
  <Code Byte="16#DE#">16#017D#</Code>
  <Code Byte="16#E0#">16#0105#</Code>
  <Code Byte="16#E1#">16#012F#</Code>
  <Code Byte="16#E2#">16#0101#</Code>
  <Code Byte="16#E3#">16#0107#</Code>
  <Code Byte="16#E6#">16#0119#</Code>
  <Code Byte="16#E7#">16#0113#</Code>
  <Code Byte="16#E8#">16#010D#</Code>
  <Code Byte="16#EA#">16#017A#</Code>
  <Code Byte="16#EB#">16#0117#</Code>
  <Code Byte="16#EC#">16#0123#</Code>
  <Code Byte="16#ED#">16#0137#</Code>
  <Code Byte="16#EE#">16#012B#</Code>
  <Code Byte="16#EF#">16#013C#</Code>
  <Code Byte="16#F0#">16#0161#</Code>
  <Code Byte="16#F1#">16#0144#</Code>
  <Code Byte="16#F2#">16#0146#</Code>
  <Code Byte="16#F4#">16#014D#</Code>
  <Code Byte="16#F8#">16#0173#</Code>
  <Code Byte="16#F9#">16#0142#</Code>
  <Code Byte="16#FA#">16#015B#</Code>
  <Code Byte="16#FB#">16#016B#</Code>
  <Code Byte="16#FD#">16#017C#</Code>
  <Code Byte="16#FE#">16#017E#</Code>
  <Code Byte="16#FF#">16#2019#</Code>
</Map>

=== malaise/ada/usr/tests/data/ISO-8859-11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Map SYSTEM "Byte2unicode.dtd">
<Map>
  <Code Byte="16#A1#">16#0E01#</Code>
  <Code Byte="16#A2#">16#0E02#</Code>
  <Code Byte="16#A3#">16#0E03#</Code>
  <Code Byte="16#A4#">16#0E04#</Code>
  <Code Byte="16#A5#">16#0E05#</Code>
  <Code Byte="16#A6#">16#0E06#</Code>
  <Code Byte="16#A7#">16#0E07#</Code>
  <Code Byte="16#A8#">16#0E08#</Code>
  <Code Byte="16#A9#">16#0E09#</Code>
  <Code Byte="16#AA#">16#0E0A#</Code>
  <Code Byte="16#AB#">16#0E0B#</Code>
  <Code Byte="16#AC#">16#0E0C#</Code>
  <Code Byte="16#AD#">16#0E0D#</Code>
  <Code Byte="16#AE#">16#0E0E#</Code>
  <Code Byte="16#AF#">16#0E0F#</Code>
  <Code Byte="16#B0#">16#0E10#</Code>
  <Code Byte="16#B1#">16#0E11#</Code>
  <Code Byte="16#B2#">16#0E12#</Code>
  <Code Byte="16#B3#">16#0E13#</Code>
  <Code Byte="16#B4#">16#0E14#</Code>
  <Code Byte="16#B5#">16#0E15#</Code>
  <Code Byte="16#B6#">16#0E16#</Code>
  <Code Byte="16#B7#">16#0E17#</Code>
  <Code Byte="16#B8#">16#0E18#</Code>
  <Code Byte="16#B9#">16#0E19#</Code>
  <Code Byte="16#BA#">16#0E1A#</Code>
  <Code Byte="16#BB#">16#0E1B#</Code>
  <Code Byte="16#BC#">16#0E1C#</Code>
  <Code Byte="16#BD#">16#0E1D#</Code>
  <Code Byte="16#BE#">16#0E1E#</Code>
  <Code Byte="16#BF#">16#0E1F#</Code>
  <Code Byte="16#C0#">16#0E20#</Code>
  <Code Byte="16#C1#">16#0E21#</Code>
  <Code Byte="16#C2#">16#0E22#</Code>
  <Code Byte="16#C3#">16#0E23#</Code>
  <Code Byte="16#C4#">16#0E24#</Code>
  <Code Byte="16#C5#">16#0E25#</Code>
  <Code Byte="16#C6#">16#0E26#</Code>
  <Code Byte="16#C7#">16#0E27#</Code>
  <Code Byte="16#C8#">16#0E28#</Code>
  <Code Byte="16#C9#">16#0E29#</Code>
  <Code Byte="16#CA#">16#0E2A#</Code>
  <Code Byte="16#CB#">16#0E2B#</Code>
  <Code Byte="16#CC#">16#0E2C#</Code>
  <Code Byte="16#CD#">16#0E2D#</Code>
  <Code Byte="16#CE#">16#0E2E#</Code>
  <Code Byte="16#CF#">16#0E2F#</Code>
  <Code Byte="16#D0#">16#0E30#</Code>
  <Code Byte="16#D1#">16#0E31#</Code>
  <Code Byte="16#D2#">16#0E32#</Code>
  <Code Byte="16#D3#">16#0E33#</Code>
  <Code Byte="16#D4#">16#0E34#</Code>
  <Code Byte="16#D5#">16#0E35#</Code>
  <Code Byte="16#D6#">16#0E36#</Code>
  <Code Byte="16#D7#">16#0E37#</Code>
  <Code Byte="16#D8#">16#0E38#</Code>
  <Code Byte="16#D9#">16#0E39#</Code>
  <Code Byte="16#DA#">16#0E3A#</Code>
  <Code Byte="16#DF#">16#0E3F#</Code>
  <Code Byte="16#E0#">16#0E40#</Code>
  <Code Byte="16#E1#">16#0E41#</Code>
  <Code Byte="16#E2#">16#0E42#</Code>
  <Code Byte="16#E3#">16#0E43#</Code>
  <Code Byte="16#E4#">16#0E44#</Code>
  <Code Byte="16#E5#">16#0E45#</Code>
  <Code Byte="16#E6#">16#0E46#</Code>
  <Code Byte="16#E7#">16#0E47#</Code>
  <Code Byte="16#E8#">16#0E48#</Code>
  <Code Byte="16#E9#">16#0E49#</Code>
  <Code Byte="16#EA#">16#0E4A#</Code>
  <Code Byte="16#EB#">16#0E4B#</Code>
  <Code Byte="16#EC#">16#0E4C#</Code>
  <Code Byte="16#ED#">16#0E4D#</Code>
  <Code Byte="16#EE#">16#0E4E#</Code>
  <Code Byte="16#EF#">16#0E4F#</Code>
  <Code Byte="16#F0#">16#0E50#</Code>
  <Code Byte="16#F1#">16#0E51#</Code>
  <Code Byte="16#F2#">16#0E52#</Code>
  <Code Byte="16#F3#">16#0E53#</Code>
  <Code Byte="16#F4#">16#0E54#</Code>
  <Code Byte="16#F5#">16#0E55#</Code>
  <Code Byte="16#F6#">16#0E56#</Code>
  <Code Byte="16#F7#">16#0E57#</Code>
  <Code Byte="16#F8#">16#0E58#</Code>
  <Code Byte="16#F9#">16#0E59#</Code>
  <Code Byte="16#FA#">16#0E5A#</Code>
  <Code Byte="16#FB#">16#0E5B#</Code>
</Map>

=== malaise/ada/usr/tests/data/ISO-8859-14.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Map SYSTEM "Byte2unicode.dtd">
<Map>
  <Code Byte="16#A1#">16#1E02#</Code>
  <Code Byte="16#A2#">16#1E03#</Code>
  <Code Byte="16#A4#">16#010A#</Code>
  <Code Byte="16#A5#">16#010B#</Code>
  <Code Byte="16#A6#">16#1E0A#</Code>
  <Code Byte="16#A8#">16#1E80#</Code>
  <Code Byte="16#AA#">16#1E82#</Code>
  <Code Byte="16#AB#">16#1E0B#</Code>
  <Code Byte="16#AC#">16#1EF2#</Code>
  <Code Byte="16#AF#">16#0178#</Code>
  <Code Byte="16#B0#">16#1E1E#</Code>
  <Code Byte="16#B1#">16#1E1F#</Code>
  <Code Byte="16#B2#">16#0120#</Code>
  <Code Byte="16#B3#">16#0121#</Code>
  <Code Byte="16#B4#">16#1E40#</Code>
  <Code Byte="16#B5#">16#1E41#</Code>
  <Code Byte="16#B7#">16#1E56#</Code>
  <Code Byte="16#B8#">16#1E81#</Code>
  <Code Byte="16#B9#">16#1E57#</Code>
  <Code Byte="16#BA#">16#1E83#</Code>
  <Code Byte="16#BB#">16#1E60#</Code>
  <Code Byte="16#BC#">16#1EF3#</Code>
  <Code Byte="16#BD#">16#1E84#</Code>
  <Code Byte="16#BE#">16#1E85#</Code>
  <Code Byte="16#BF#">16#1E61#</Code>
  <Code Byte="16#D0#">16#0174#</Code>
  <Code Byte="16#D7#">16#1E6A#</Code>
  <Code Byte="16#DE#">16#0176#</Code>
  <Code Byte="16#F0#">16#0175#</Code>
  <Code Byte="16#F7#">16#1E6B#</Code>
  <Code Byte="16#FE#">16#0177#</Code>
</Map>
