=== malaise/ada/reposit/Byte2unicode.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD for Byte_To_Unicode -->
<!-- +++++++++++++++++++++++ -->

<!-- All the Codes (from 0x00 to 0xFF) must be defined -->
<!-- In any order -->
<!ELEMENT Map (Code+)>

<!-- Byte can be in decimal or hexadecimal (16#zz# or 0xzz) -->
<!ATTLIST Code Byte CDATA #REQUIRED>
<!-- Code can be in decimal or hexadecimal (16#zz# or 0xzz) -->
<!ELEMENT Code (#PCDATA)>

=== malaise/ada/usr/tests/data/ISO-8859-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Map SYSTEM "Byte2unicode.dtd">
<Map>
  <Code Byte="16#A1#">16#0104#</Code>
  <Code Byte="16#A2#">16#02D8#</Code>
  <Code Byte="16#A3#">16#0141#</Code>
  <Code Byte="16#A5#">16#013D#</Code>
  <Code Byte="16#A6#">16#015A#</Code>
  <Code Byte="16#A9#">16#0160#</Code>
  <Code Byte="16#AA#">16#015E#</Code>
  <Code Byte="16#AB#">16#0164#</Code>
  <Code Byte="16#AC#">16#0179#</Code>
  <Code Byte="16#AE#">16#017D#</Code>
  <Code Byte="16#AF#">16#017B#</Code>
  <Code Byte="16#B1#">16#0105#</Code>
  <Code Byte="16#B2#">16#02DB#</Code>
  <Code Byte="16#B3#">16#0142#</Code>
  <Code Byte="16#B5#">16#013E#</Code>
  <Code Byte="16#B6#">16#015B#</Code>
  <Code Byte="16#B7#">16#02C7#</Code>
  <Code Byte="16#B9#">16#0161#</Code>
  <Code Byte="16#BA#">16#015F#</Code>
  <Code Byte="16#BB#">16#0165#</Code>
  <Code Byte="16#BC#">16#017A#</Code>
  <Code Byte="16#BD#">16#02DD#</Code>
  <Code Byte="16#BE#">16#017E#</Code>
  <Code Byte="16#BF#">16#017C#</Code>
  <Code Byte="16#C0#">16#0154#</Code>
  <Code Byte="16#C3#">16#0102#</Code>
  <Code Byte="16#C5#">16#0139#</Code>
  <Code Byte="16#C6#">16#0106#</Code>
  <Code Byte="16#C8#">16#010C#</Code>
  <Code Byte="16#CA#">16#0118#</Code>
  <Code Byte="16#CC#">16#011A#</Code>
  <Code Byte="16#CF#">16#010E#</Code>
  <Code Byte="16#D0#">16#0110#</Code>
  <Code Byte="16#D1#">16#0143#</Code>
  <Code Byte="16#D2#">16#0147#</Code>
  <Code Byte="16#D5#">16#0150#</Code>
  <Code Byte="16#D8#">16#0158#</Code>
  <Code Byte="16#D9#">16#016E#</Code>
  <Code Byte="16#DB#">16#0170#</Code>
  <Code Byte="16#DE#">16#0162#</Code>
  <Code Byte="16#E0#">16#0155#</Code>
  <Code Byte="16#E3#">16#0103#</Code>
  <Code Byte="16#E5#">16#013A#</Code>
  <Code Byte="16#E6#">16#0107#</Code>
  <Code Byte="16#E8#">16#010D#</Code>
  <Code Byte="16#EA#">16#0119#</Code>
  <Code Byte="16#EC#">16#011B#</Code>
  <Code Byte="16#EF#">16#010F#</Code>
  <Code Byte="16#F0#">16#0111#</Code>
  <Code Byte="16#F1#">16#0144#</Code>
  <Code Byte="16#F2#">16#0148#</Code>
  <Code Byte="16#F5#">16#0151#</Code>
  <Code Byte="16#F8#">16#0159#</Code>
  <Code Byte="16#F9#">16#016F#</Code>
  <Code Byte="16#FB#">16#0171#</Code>
  <Code Byte="16#FE#">16#0163#</Code>
  <Code Byte="16#FF#">16#02D9#</Code>
</Map>

=== malaise/ada/usr/tests/data/ISO-8859-15.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Map SYSTEM "Byte2unicode.dtd">
<Map>
  <Code Byte="16#A4#">16#20AC#</Code>
  <Code Byte="16#A6#">16#0160#</Code>
  <Code Byte="16#A8#">16#0161#</Code>
  <Code Byte="16#B4#">16#017D#</Code>
  <Code Byte="16#B8#">16#017E#</Code>
  <Code Byte="16#BC#">16#0152#</Code>
  <Code Byte="16#BD#">16#0153#</Code>
  <Code Byte="16#BE#">16#0178#</Code>
</Map>

=== malaise/ada/usr/tests/data/ISO-8859-4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Map SYSTEM "Byte2unicode.dtd">
<Map>
  <Code Byte="16#A1#">16#0104#</Code>
  <Code Byte="16#A2#">16#0138#</Code>
  <Code Byte="16#A3#">16#0156#</Code>
  <Code Byte="16#A5#">16#0128#</Code>
  <Code Byte="16#A6#">16#013B#</Code>
  <Code Byte="16#A9#">16#0160#</Code>
  <Code Byte="16#AA#">16#0112#</Code>
  <Code Byte="16#AB#">16#0122#</Code>
  <Code Byte="16#AC#">16#0166#</Code>
  <Code Byte="16#AE#">16#017D#</Code>
  <Code Byte="16#B1#">16#0105#</Code>
  <Code Byte="16#B2#">16#02DB#</Code>
  <Code Byte="16#B3#">16#0157#</Code>
  <Code Byte="16#B5#">16#0129#</Code>
  <Code Byte="16#B6#">16#013C#</Code>
  <Code Byte="16#B7#">16#02C7#</Code>
  <Code Byte="16#B9#">16#0161#</Code>
  <Code Byte="16#BA#">16#0113#</Code>
  <Code Byte="16#BB#">16#0123#</Code>
  <Code Byte="16#BC#">16#0167#</Code>
  <Code Byte="16#BD#">16#014A#</Code>
  <Code Byte="16#BE#">16#017E#</Code>
  <Code Byte="16#BF#">16#014B#</Code>
  <Code Byte="16#C0#">16#0100#</Code>
  <Code Byte="16#C7#">16#012E#</Code>
  <Code Byte="16#C8#">16#010C#</Code>
  <Code Byte="16#CA#">16#0118#</Code>
  <Code Byte="16#CC#">16#0116#</Code>
  <Code Byte="16#CF#">16#012A#</Code>
  <Code Byte="16#D0#">16#0110#</Code>
  <Code Byte="16#D1#">16#0145#</Code>
  <Code Byte="16#D2#">16#014C#</Code>
  <Code Byte="16#D3#">16#0136#</Code>
  <Code Byte="16#D9#">16#0172#</Code>
  <Code Byte="16#DD#">16#0168#</Code>
  <Code Byte="16#DE#">16#016A#</Code>
  <Code Byte="16#E0#">16#0101#</Code>
  <Code Byte="16#E7#">16#012F#</Code>
  <Code Byte="16#E8#">16#010D#</Code>
  <Code Byte="16#EA#">16#0119#</Code>
  <Code Byte="16#EC#">16#0117#</Code>
  <Code Byte="16#EF#">16#012B#</Code>
  <Code Byte="16#F0#">16#0111#</Code>
  <Code Byte="16#F1#">16#0146#</Code>
  <Code Byte="16#F2#">16#014D#</Code>
  <Code Byte="16#F3#">16#0137#</Code>
  <Code Byte="16#F9#">16#0173#</Code>
  <Code Byte="16#FD#">16#0169#</Code>
  <Code Byte="16#FE#">16#016B#</Code>
  <Code Byte="16#FF#">16#02D9#</Code>
</Map>

=== malaise/ada/usr/tests/data/ISO-8859-6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Map SYSTEM "Byte2unicode.dtd">
<Map>
  <Code Byte="16#AC#">16#060C#</Code>
  <Code Byte="16#BB#">16#061B#</Code>
  <Code Byte="16#BF#">16#061F#</Code>
  <Code Byte="16#C1#">16#0621#</Code>
  <Code Byte="16#C2#">16#0622#</Code>
  <Code Byte="16#C3#">16#0623#</Code>
  <Code Byte="16#C4#">16#0624#</Code>
  <Code Byte="16#C5#">16#0625#</Code>
  <Code Byte="16#C6#">16#0626#</Code>
  <Code Byte="16#C7#">16#0627#</Code>
  <Code Byte="16#C8#">16#0628#</Code>
  <Code Byte="16#C9#">16#0629#</Code>
  <Code Byte="16#CA#">16#062A#</Code>
  <Code Byte="16#CB#">16#062B#</Code>
  <Code Byte="16#CC#">16#062C#</Code>
  <Code Byte="16#CD#">16#062D#</Code>
  <Code Byte="16#CE#">16#062E#</Code>
  <Code Byte="16#CF#">16#062F#</Code>
  <Code Byte="16#D0#">16#0630#</Code>
  <Code Byte="16#D1#">16#0631#</Code>
  <Code Byte="16#D2#">16#0632#</Code>
  <Code Byte="16#D3#">16#0633#</Code>
  <Code Byte="16#D4#">16#0634#</Code>
  <Code Byte="16#D5#">16#0635#</Code>
  <Code Byte="16#D6#">16#0636#</Code>
  <Code Byte="16#D7#">16#0637#</Code>
  <Code Byte="16#D8#">16#0638#</Code>
  <Code Byte="16#D9#">16#0639#</Code>
  <Code Byte="16#DA#">16#063A#</Code>
  <Code Byte="16#E0#">16#0640#</Code>
  <Code Byte="16#E1#">16#0641#</Code>
  <Code Byte="16#E2#">16#0642#</Code>
  <Code Byte="16#E3#">16#0643#</Code>
  <Code Byte="16#E4#">16#0644#</Code>
  <Code Byte="16#E5#">16#0645#</Code>
  <Code Byte="16#E6#">16#0646#</Code>
  <Code Byte="16#E7#">16#0647#</Code>
  <Code Byte="16#E8#">16#0648#</Code>
  <Code Byte="16#E9#">16#0649#</Code>
  <Code Byte="16#EA#">16#064A#</Code>
  <Code Byte="16#EB#">16#064B#</Code>
  <Code Byte="16#EC#">16#064C#</Code>
  <Code Byte="16#ED#">16#064D#</Code>
  <Code Byte="16#EE#">16#064E#</Code>
  <Code Byte="16#EF#">16#064F#</Code>
  <Code Byte="16#F0#">16#0650#</Code>
  <Code Byte="16#F1#">16#0651#</Code>
  <Code Byte="16#F2#">16#0652#</Code>
</Map>

=== malaise/ada/usr/tests/data/ISO-8859-10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Map SYSTEM "Byte2unicode.dtd">
<Map>
  <Code Byte="16#A1#">16#0104#</Code>
  <Code Byte="16#A2#">16#0112#</Code>
  <Code Byte="16#A3#">16#0122#</Code>
  <Code Byte="16#A4#">16#012A#</Code>
  <Code Byte="16#A5#">16#0128#</Code>
  <Code Byte="16#A6#">16#0136#</Code>
  <Code Byte="16#A8#">16#013B#</Code>
  <Code Byte="16#A9#">16#0110#</Code>
  <Code Byte="16#AA#">16#0160#</Code>
  <Code Byte="16#AB#">16#0166#</Code>
  <Code Byte="16#AC#">16#017D#</Code>
  <Code Byte="16#AE#">16#016A#</Code>
  <Code Byte="16#AF#">16#014A#</Code>
  <Code Byte="16#B1#">16#0105#</Code>
  <Code Byte="16#B2#">16#0113#</Code>
  <Code Byte="16#B3#">16#0123#</Code>
  <Code Byte="16#B4#">16#012B#</Code>
  <Code Byte="16#B5#">16#0129#</Code>
  <Code Byte="16#B6#">16#0137#</Code>
  <Code Byte="16#B8#">16#013C#</Code>
  <Code Byte="16#B9#">16#0111#</Code>
  <Code Byte="16#BA#">16#0161#</Code>
  <Code Byte="16#BB#">16#0167#</Code>
  <Code Byte="16#BC#">16#017E#</Code>
  <Code Byte="16#BD#">16#2015#</Code>
  <Code Byte="16#BE#">16#016B#</Code>
  <Code Byte="16#BF#">16#014B#</Code>
  <Code Byte="16#C0#">16#0100#</Code>
  <Code Byte="16#C7#">16#012E#</Code>
  <Code Byte="16#C8#">16#010C#</Code>
  <Code Byte="16#CA#">16#0118#</Code>
  <Code Byte="16#CC#">16#0116#</Code>
  <Code Byte="16#D1#">16#0145#</Code>
  <Code Byte="16#D2#">16#014C#</Code>
  <Code Byte="16#D7#">16#0168#</Code>
  <Code Byte="16#D9#">16#0172#</Code>
  <Code Byte="16#E0#">16#0101#</Code>
  <Code Byte="16#E7#">16#012F#</Code>
  <Code Byte="16#E8#">16#010D#</Code>
  <Code Byte="16#EA#">16#0119#</Code>
  <Code Byte="16#EC#">16#0117#</Code>
  <Code Byte="16#F1#">16#0146#</Code>
  <Code Byte="16#F2#">16#014D#</Code>
  <Code Byte="16#F7#">16#0169#</Code>
  <Code Byte="16#F9#">16#0173#</Code>
  <Code Byte="16#FF#">16#0138#</Code>
</Map>
