=== malaise/ada/reposit/Channels.dtd
<?xml version="1.0" encoding="Utf-8"?>

<!-- DTD for the Channel package -->
<!-- +++++++++++++++++++++++++++ -->

<!ELEMENT Channels (Channel)*>

<!-- Each channel has a unique name and defines a list of hosts -->
<!ELEMENT Channel (Host)*>
<!ATTLIST Channel Name ID #REQUIRED>

<!-- Host name or IP address -->
<!ELEMENT Host (#PCDATA)>

=== malaise/ada/usr/tests/data/channels.xml
<?xml version="1.0" encoding="Utf-8"?>
<!DOCTYPE Channels SYSTEM "Channels.dtd">

<Channels>
  <Channel Name="test_tcp">
    <Host>ulysse</Host>
    <Host>penelope</Host>
    <Host>telemaque</Host>
  </Channel>

  <Channel Name="iqobject">
    <Host>cofserv</Host>
    <Host>csciint22</Host>
  </Channel>
</Channels>

=== malaise/ada/usr/misc/test_tcp.xml
<?xml version="1.0" encoding="Utf-8"?>
<!-- An example of tcp channels configuration file -->
<!DOCTYPE Channels SYSTEM "../../reposit/Channels.dtd">

<Channels>
  <Channel Name="test_tcp">
    <Host>uc1</Host>
    <Host>uc2</Host>
    <Host>uc3</Host>
    <Host>uc4</Host>
    <Host>uc5</Host>
    <Host>uc6</Host>
    <Host>uc7</Host>
    <Host>plt2</Host>
    <Host>fs1</Host>
  </Channel>
</Channels>
